#!/usr/bin/with-contenv bash

s6-setuidgid abc /config/gmodserver start

until [[ -e /config/serverfiles/logs && -e /config/serverfiles/gmodserver.pid ]]; do
sleep 1s
done

exec \
	s6-setuidgid abc tail -F -q --pid="$(cat /config/serverfiles/gmodserver.pid)" \
	"$(find /config/serverfiles/logs -printf '%C@ %p\n' |sort | head -n 2)"
