#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/serverfiles

# fetch installer
if [ ! -e /config/gmodserver ]; then
wget -O /config/linuxgsm.sh http://gameservermanagers.com/dl/linuxgsm.sh
chmod +x /config/linuxgsm.sh
bash linuxgsm.sh gmodserver
fi

# permissions
chown abc:abc -R /config

if [ ! -f /config/gmodserver ]; then
cd /config || exit
s6-setuidgid abc /config/gmodserver install
fi
